config/routes.rb
OnAppTask::Application.routes.draw do
	
	root to: "tickets#index"
	
	resources :tickets, :only => [:index, :create, :new, :show, :update] do
		get 'login', :on => :collection
		post 'authenticate', :on => :collection
		get 'logout', :on => :collection
	end

	resources :sessions, :only => [:new, :create, :destroy]

	namespace :backend do
	  root to: "tickets#index"
	  resources :tickets, :only => [:index, :show, :update] do
			post 'search', :on => :collection
		end
	end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :login, :password_digest
	has_secure_password
	
	validates :login, :password_digest, :presence => true
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :ticket
  attr_accessible :text, :changes, :author

	validates :text, :author, :presence => true
end

app/models/status.rb
class Status < ActiveRecord::Base
	has_many :tickets
  attr_accessible :name

	validates :name, :presence => true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :employee
	belongs_to :status
  attr_accessible :customer_mail, :customer_name, :subject, :department, :description, :employee_id
	
	has_many :replies, :dependent => :destroy

	def self.all_departments()
		%w(billing documentation technical)
	end

	def self.all_statuses
		Status.all
	end

	validates :customer_mail, :customer_name, :department, :subject, :status, :presence => true
	validates :customer_mail, :format => { :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ }
	validates :department, :inclusion => { :in => Ticket.all_departments()}

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

	private

	def current_user
		session[:employee_id]? Employee.find(session[:employee_id]) : nil
	end
	
	def authenticate
		if current_user.nil?
			render :status => :forbidden, :text => "Forbidden!!!"
		end
	end
	
	helper_method :current_user
end

app/controllers/backend/application_controller.rb
class Backend::ApplicationController < ApplicationController
	
	before_filter :authenticate
	
end

app/controllers/backend/tickets_controller.rb
class Backend::TicketsController < Backend::ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
		unless %w(new open hold closed).include?(params[:scope])
			redirect_to backend_tickets_path :scope => "new"
			return
		end
		case params[:scope]
			when "new"
				@tickets = Ticket.order("updated_at DESC").where(:employee_id => nil)
			when "open"
				@tickets = (Status.find_by_name('Waiting for Staff Response').tickets+Status.find_by_name('Waiting for Customer').tickets).sort_by {|ticket| -ticket.updated_at.to_f}
			when "hold"
				@tickets = Status.find_by_name('On Hold').tickets.order("updated_at DESC")
			when "closed"
					@tickets = @tickets = (Status.find_by_name('Cancelled').tickets+Status.find_by_name('Completed').tickets).sort_by {|ticket| -ticket.updated_at.to_f}
		end
		@scope = params[:scope]
    #@tickets = Ticket.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])
		@reply = @ticket.replies.build
		
		@scope = params[:scope]
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])
		changes = ""
		new_employee = params[:ticket][:employee_id].nil? || params[:ticket][:employee_id].empty?  ? nil : Employee.find(params[:ticket][:employee_id])
		unless new_employee == @ticket.employee
			changes += "> Responsible changed from #{@ticket.employee ? @ticket.employee.login : "None"} to #{new_employee.login}"
			@ticket.employee = new_employee
		end
		new_status = params[:ticket][:status_id].nil? || params[:ticket][:status_id].empty?  ? nil : Status.find(params[:ticket][:status_id])
		unless new_status == @ticket.status
			changes += $/ + "> Status changed from \"#{@ticket.status ? @ticket.status.name : "None"}\" to \"#{new_status.name}\""
			@ticket.status = new_status
		end
		@reply = @ticket.replies.build(params[:reply])
		@reply.meta = changes
		@reply.author = current_user.login
    respond_to do |format|
      if @ticket.valid? && @reply.valid?
				@ticket.save
				@reply.save
				CustomerSupport.update_ticket_email(@ticket,@reply).deliver
        format.html { redirect_to backend_ticket_path(@ticket), notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

	def search
		if params[:search][:search].empty?
			@tickets = []
		else
			if Ticket.exists? params[:search][:search]
				redirect_to backend_ticket_path Ticket.find params[:search][:search]
			else
				@tickets = Ticket.order("updated_at DESC").where('subject LIKE ?', "%#{params[:search][:search]}%").all
			end
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
		@login = current_user.login unless current_user.nil?
  end

  def create
	  employee = Employee.find_by_login(params[:login])
	  if employee && employee.authenticate(params[:password])
	    session[:employee_id] = employee.id
	    redirect_to backend_root_path, :notice => "Logged in!"
	  else
	    flash.now.alert = "Invalid login or password"
	    render "new"
	  end
	end

	def destroy
	  session[:employee_id] = nil
	  redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.find_all_by_customer_mail session[:email] unless session[:email].nil?
		@email = session[:email]
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])
		@reply = @ticket.replies.build

		if @ticket.customer_mail != session[:email]
			session[:path] = ticket_path @ticket
			redirect_to login_tickets_path, notice: 'Please enter an email that is associated with a ticket you are trying to access'
		else
    	respond_to do |format|
      	format.html # show.html.erb
      	format.json { render json: @ticket }
    	end
		end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new
		@ticket.customer_mail ||= session[:email]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])
		@ticket.status = Status.find_by_name 'Waiting for Staff Response'
    respond_to do |format|
      if @ticket.save
				session[:email] = params[:ticket][:customer_mail]
				CustomerSupport.new_ticket_email(@ticket).deliver
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

	# PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])
		@ticket.status = Status.find_by_name 'Waiting for Staff Response'
		@reply = @ticket.replies.build(params[:reply])
		@reply.author = @ticket.customer_name
    respond_to do |format|
      if @reply.save
				@ticket.save
        format.html { redirect_to ticket_path(@ticket), notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

	# GET /tickets/login
	def login
		@email = session[:email]
	end
	
	def authenticate
		session[:email] = params[:email] if params.key? :email
		redirect_to session[:path] || tickets_path
		session[:path] = nil
	end
	
	# GET /tickets/logout
	def logout
		session[:email] = nil
		redirect_to tickets_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backend/application_helper.rb
module Backend::ApplicationHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
	
	def available_departments
		Ticket.all_departments
	end
	
	def available_statuses
		Ticket.all_statuses
	end
	
end

app/views/backend/tickets/_table.html.haml
%table
  %tr
    %th ID
    %th Subject
    %th Customer
    %th Status
    %th Responsible
    %th Department
    %th
  - @tickets.each do |ticket|
    %tr
      %td= ticket.id
      %td= ticket.subject[0,20]
      %td= ticket.customer_name
      %td= ticket.status.name
      %td= ticket.employee ? ticket.employee.login : "None"
      %td= ticket.department
      %td= link_to 'Show', backend_ticket_path(ticket, :scope => @scope)

app/views/backend/tickets/index.html.haml
= link_to 'Logout', "/sessions/1", :confirm => 'Are you sure?', :method => :delete

%h1 Listing tickets

%nav
  =link_to 'New', backend_tickets_path(:scope => "new")
  =link_to 'Open', backend_tickets_path(:scope => "open")
  =link_to 'On Hold', backend_tickets_path(:scope => "hold")
  =link_to 'Closed', backend_tickets_path(:scope => "closed")

= form_tag search_backend_tickets_path do
  = label_tag :search, "Search:"
  = text_field :search, "search"
  = submit_tag "Submit"

= render "table"

app/views/backend/tickets/search.html.haml
= link_to 'Logout', "/sessions/1", :confirm => 'Are you sure?', :method => :delete

%h1 Search results

=link_to 'Back to index', backend_tickets_path

-if @tickets.nil? || @tickets.empty?
  %p nothing found
-else
  = render "table"

app/views/backend/tickets/show.html.haml
= link_to 'Logout', "/sessions/1", :confirm => 'Are you sure?', :method => :delete

%p
  %b Customer name:
  = @ticket.customer_name
%p
  %b Customer mail:
  = @ticket.customer_mail
%p
  %b Department:
  = @ticket.department
%p
  %b Status:
  = @ticket.status.name
%p
  %b Employee:
  = @ticket.employee ? @ticket.employee.login : "None"
%p
  %b Description:
  = @ticket.description

= form_for([:backend ,@ticket]) do |f|
  - if @ticket.errors.any?
    #error_explanation
      %h2
        = pluralize(@ticket.errors.count, "error")
        prohibited this ticket from being saved:
      %ul
        - @ticket.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :status
    %br/
    = f.collection_select :status_id, Status.all, :id, :name
  .field
    = f.label :employee
    %br/
    = f.collection_select :employee_id, Employee.all, :id, :login, :include_blank => (@ticket.employee.nil?)
    
  = fields_for @reply do |reply_f|
    .field
      = reply_f.label :text, "Comment:"
      %br/
      = reply_f.text_area :text
    
  .actions
    = f.submit
    

- unless @ticket.replies.nil?
  - @ticket.replies.order("created_at DESC").each do |reply|
    .reply
      %p
        At
        = reply.created_at
        by
        = reply.author
      -unless reply.meta.nil? || reply.meta.empty?
        %pre= reply.meta
      %p= reply.text
        

=link_to 'Back', backend_tickets_path(:scope => @scope)

app/views/customer_support/new_ticket_email.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %body
    %h1
      Welcome, #{@ticket.customer_name}
    %p
      We've received your ticket and will soon contact you.
      %br/
    %p
      Your ticket's id is: #{@ticket.id}.
    %p
      You can view your ticket by visiting: 
      = link_to "this link", ticket_url(@ticket)

app/views/customer_support/new_ticket_email.text.haml
:plain
  Welcome, #{@ticket.customer_name}
  
  We've received your ticket and will soon contact you.

  Your ticket's id is: #{@ticket.id}.

  You can view your ticket by visiting: #{ticket_url @ticket}

app/views/customer_support/notification_email.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %body
    %h1
      Welcome, #{@ticket.customer_name}
    %p
      We've received your ticket and will soon contact you.
      %br/
    %p
      Your ticket's id is: #{@ticket.id}.
    %p
      You can view your ticket by visiting: 
      = link_to "this link", ticket_url(@ticket)

app/views/customer_support/notification_email.text.haml
:plain
  Welcome, #{@ticket.customer_name}
  
  We've received your ticket and will soon contact you.

  Your ticket's id is: #{@ticket.id}.

  You can view your ticket by visiting: #{ticket_url @ticket}

app/views/customer_support/update_ticket_email.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %body
    %h1
      Dear, #{@ticket.customer_name}
    %p
      #{@reply.author} has commented on your ticket: #{@ticket.subject}:
      %br/
      = @reply.text
    -unless @reply.meta.nil? || @reply.meta.empty?
      %p
        The next changes have been made:
      %pre
        = @reply.meta
    %p
      Your ticket's id is: #{@ticket.id}.
    %p
      You can view your ticket by visiting: 
      = link_to "this link", ticket_url(@ticket)

app/views/customer_support/update_ticket_email.text.haml
:plain
  Dear, #{@ticket.customer_name}
  
  #{@reply.author} has commented on your ticket: #{@ticket.subject}:
  
  #{@reply.text}
  
  Your ticket's id is: #{@ticket.id}.

  You can view your ticket by visiting: #{ticket_url @ticket}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title OnAppTask
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %p#notice= notice
    %p#alert= alert
    = yield

app/views/tickets/index.html.haml
%h1 Listing tickets

- if @email
  %p
    Your email is: #{@email} [
    = link_to 'change', login_tickets_path
    ] [
    = link_to 'sign out', logout_tickets_path
    ]
- else
  %p
    To see your questions
    = link_to 'sign in', login_tickets_path
    with your email

= link_to 'New Question', new_ticket_path
  
-unless @tickets.nil?
  - @tickets.each do |ticket|
    .ticket
      %h3= ticket.subject
      %p Department: #{ticket.department} | Responsible: #{ticket.employee || "None"} | Status: #{ticket.status}
      = link_to 'More…', ticket

app/views/tickets/login.html.haml
%p Enter your email to see your questions

=form_tag authenticate_tickets_path do
  .field
    = label_tag "Mail:"
    %br/
    = text_field_tag :email, @email
  .actions
    = submit_tag
    
=link_to 'Back', tickets_path

app/views/tickets/new.html.haml
%h1 New ticket
= form_for(@ticket) do |f|
  - if @ticket.errors.any?
    #error_explanation
      %h2
        = pluralize(@ticket.errors.count, "error")
        prohibited this ticket from being saved:
      %ul
        - @ticket.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label "Name"
    %br/
    = f.text_field :customer_name
  .field
    = f.label "Email address"
    %br/
    = f.text_field :customer_mail
  %br/
  .field
    = f.label :subject
    %br/
    = f.text_field :subject
  .field
    = f.label :department
    %br/
    = f.select :department, available_departments
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/tickets/show.html.haml
%p
  %b Customer name:
  = @ticket.customer_name
%p
  %b Customer mail:
  = @ticket.customer_mail
%p
  %b Question subject:
  = @ticket.subject
%p
  %b Department:
  = @ticket.department
%p
  %b Status:
  = @ticket.status.name
%p
  %b Responsible:
  = @ticket.employee ? @ticket.employee.login : "None"
%p
  %b Description:
  %br/
  = @ticket.description

= form_for(@ticket) do |f|
  - if @ticket.errors.any?
    #error_explanation
      %h2
        = pluralize(@ticket.errors.count, "error")
        prohibited this ticket from being saved:
      %ul
        - @ticket.errors.full_messages.each do |msg|
          %li= msg
          
  = fields_for @reply do |reply_f|
    .field
      = reply_f.label :text, "Comment:"
      %br/
      = reply_f.text_area :text

  .actions
    = f.submit

- unless @ticket.replies.nil?
  - @ticket.replies.order("created_at DESC").each do |reply|
    .reply
      %p
        At
        = reply.created_at
        by
        = reply.author
      -unless reply.meta.nil? || reply.meta.empty?
        %pre= reply.meta
      %p= reply.text

=link_to 'Back', tickets_path